// Auto-generated by scripts/register_kb.py. Do not edit by hand.
//
// Maps a Tavus knowledge-base document_name to the compound's top available
// evidence tier and a short descriptor, so the Sources panel can badge a cited
// dossier from registry facts rather than a fragile document-name heuristic.
// The level is the highest tier with available items in that dossier
// (4 = published RCT ... 1 = anecdote); the descriptor is the dossier summary.

export interface DossierTierEntry {
  /** Registry compound id. */
  compoundId: number;
  /** Highest evidence tier with available items (4 = RCT ... 1 = anecdote). */
  level: 1 | 2 | 3 | 4;
  /** One-line evidence characterization for the Sources panel. */
  descriptor: string;
}

export const dossierTiers: Record<string, DossierTierEntry> = {
  "BPC-157 evidence dossier": {
    compoundId: 1,
    level: 4,
    descriptor: "Hyped healing peptide. ~all evidence preclinical; only 2 registered human trials ever. WADA-banned.",
  },
  "Semaglutide evidence dossier": {
    compoundId: 2,
    level: 4,
    descriptor: "FDA-approved. Robust RCT base (SELECT). The benchmark every meme peptide is measured against.",
  },
  "Tirzepatide evidence dossier": {
    compoundId: 3,
    level: 4,
    descriptor: "FDA-approved. Outperformed semaglutide head-to-head (SURMOUNT-5).",
  },
  "TB-500 evidence dossier": {
    compoundId: 4,
    level: 4,
    descriptor: "Tissue-repair peptide. Only tiny early-phase ophthalmic trials; not approved. WADA-banned.",
  },
  "Ipamorelin evidence dossier": {
    compoundId: 5,
    level: 4,
    descriptor: "GH secretagogue. No registered human efficacy trials surfaced; not approved. WADA-banned (S2).",
  },
  "CJC-1295 evidence dossier": {
    compoundId: 6,
    level: 4,
    descriptor: "GHRH analogue, often stacked with ipamorelin. Not approved. WADA-banned (S2).",
  },
  "Thymosin-alpha-1 evidence dossier": {
    compoundId: 7,
    level: 4,
    descriptor: "Approved in several countries (Zadaxin) but not FDA-approved. Phase 3 sepsis trial (TESTS) was negative.",
  },
  "Tesamorelin evidence dossier": {
    compoundId: 8,
    level: 4,
    descriptor: "FDA-approved (Egrifta) for HIV lipodystrophy. Raises IGF-1 within normal range; no glycemic worsening in trials.",
  },
  "Melanotan-II evidence dossier": {
    compoundId: 9,
    level: 4,
    descriptor: "Tanning/libido peptide with documented harms (nausea, priapism, mole darkening). Not approved.",
  },
  "GHK-Cu evidence dossier": {
    compoundId: 10,
    level: 4,
    descriptor: "Copper tripeptide marketed cosmetically. Not approved as a drug for systemic use.",
  },
  "Sermorelin evidence dossier": {
    compoundId: 11,
    level: 2,
    descriptor: "Former FDA-approved GHRH analogue (Geref), withdrawn from US market; now compounded/research use.",
  },
  "Retatrutide evidence dossier": {
    compoundId: 12,
    level: 4,
    descriptor: "Investigational triple agonist (Eli Lilly). In Phase 3; not yet approved.",
  },
};
